Add blog post for clients
memgraph/blog pull request #1
Opened 2019-05-31 12:42 UTC by tomicm

2019-05-31 12:48 UTC, gitbuda commented
Please move the markdown file to a top-level folder because some blog posts might have attached resources. The folder name should match the blog post title. It probably makes sense to rename the file to README.md because GitHub will automatically render the content.

2019-05-31 12:49 UTC, gitbuda requested changes
Please move the markdown file to a top-level folder because some blog posts might have attached resources. The folder name should match the blog post title. It probably makes sense to rename the file to `README.md` because GitHub will automatically render the content.

2019-05-31 13:30 UTC, gitbuda commented
It also makes sense to use this https://jekyllrb.com/docs/posts as a guide.

2019-05-31 13:34 UTC, tomicm commented
I've changed the blog post to Jekyll format after an offline discussion.

2019-05-31 14:56 UTC, karimtrai commented on client-blog-post.md
> +well as Memgraph CLI are now published. You can find their GitHub repositories
Define (CLI) because it's the first time it's used in the article.

2019-05-31 14:56 UTC, karimtrai commented on client-blog-post.md
> +well as Memgraph CLI are now published. You can find their GitHub repositories
Find their respective GitHub repositories here

2019-05-31 14:56 UTC, karimtrai commented on client-blog-post.md
> +Memgraph C driver, [mgclient], serves as a base for both [pymgclient] and
The Memgraph C driver

2019-05-31 14:56 UTC, karimtrai commented on client-blog-post.md
> +Memgraph command line interface, [mgconsole], also has to be installed from
The Memgraph

2019-05-31 14:56 UTC, karimtrai commented on client-blog-post.md
> +Python driver is compliant with DB-API 2.0 specification, so using it should
The Python

2019-05-31 14:56 UTC, karimtrai commented on client-blog-post.md
> +Here's an example showing how to use Memgraph command line interface:
The Memgraph command line interface

2019-05-31 14:56 UTC, karimtrai commented on client-blog-post.md
> +
Maybe add a sentence about what's to come next. Something like(e.i. We will now install mgclient, pymgclient and mgconsole and run a few basic queries)

2019-05-31 14:56 UTC, karimtrai commented on client-blog-post.md
> +
Add a conclusion sentence like (e.i. We have now installed x, y, and z and learned how to ... you are now ready to do x,y and z and here are a few next steps)

2019-05-31 15:39 UTC, karimtrai commented on 2019-05-31-official-memgraph-drivers-are-out.md
> +We will show you how to setup [mgclient], [pymgclient] and [mgconsole] and run
We will now learn how to install ...

2019-07-20 11:52 UTC, gitbuda approved these changes

2019-07-20 11:52 UTC, merged